site_name: Modelos OSI y TCP/IP
docs_dir: 'md'
site_dir: 'docs'
theme:
  name: material

nav:
  - Inicio: index.md
  - Modelo OSI: modelo_osi.md
  - Modelo TCP/IP: modelo_tcpip.md
  - Comparativa OSI vs TCP/IP: comparativa.md
  - Encapsulaci√≥n: encapsulacion.md
